<?php

use Illuminate\Database\Seeder;

class UserActionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'roles', 'action_id' => 2,],
            ['id' => 2, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 3,],
            ['id' => 3, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 4,],
            ['id' => 4, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 5,],
            ['id' => 5, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 6,],
            ['id' => 6, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'roles', 'action_id' => 6,],
            ['id' => 7, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 7,],
            ['id' => 8, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 8,],
            ['id' => 9, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'users', 'action_id' => 1,],
            ['id' => 10, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contact_companies', 'action_id' => 1,],
            ['id' => 11, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contact_companies', 'action_id' => 2,],
            ['id' => 12, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contacts', 'action_id' => 1,],
            ['id' => 13, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contacts', 'action_id' => 2,],
            ['id' => 14, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 1,],
            ['id' => 15, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 2,],
            ['id' => 16, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 3,],
            ['id' => 17, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 4,],
            ['id' => 18, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 5,],
            ['id' => 19, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 6,],
            ['id' => 20, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 7,],
            ['id' => 21, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 8,],
            ['id' => 22, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 9,],
            ['id' => 23, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 10,],
            ['id' => 24, 'user_id' => 1, 'action' => 'created', 'action_model' => 'presentacionproductos', 'action_id' => 11,],
            ['id' => 25, 'user_id' => 1, 'action' => 'created', 'action_model' => 'tipoproductos', 'action_id' => 1,],
            ['id' => 26, 'user_id' => 1, 'action' => 'created', 'action_model' => 'tipoproductos', 'action_id' => 2,],
            ['id' => 27, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 1,],
            ['id' => 28, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 2,],
            ['id' => 29, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 3,],
            ['id' => 30, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 4,],
            ['id' => 31, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 5,],
            ['id' => 32, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 6,],
            ['id' => 33, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 7,],
            ['id' => 34, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 8,],
            ['id' => 35, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 9,],
            ['id' => 36, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 10,],
            ['id' => 37, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 11,],
            ['id' => 38, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 12,],
            ['id' => 39, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 13,],
            ['id' => 40, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 14,],
            ['id' => 41, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 15,],
            ['id' => 42, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 16,],
            ['id' => 43, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 17,],
            ['id' => 44, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 18,],
            ['id' => 45, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 19,],
            ['id' => 46, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 20,],
            ['id' => 47, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 21,],
            ['id' => 48, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 22,],
            ['id' => 49, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 23,],
            ['id' => 50, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 24,],
            ['id' => 51, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 25,],
            ['id' => 52, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 26,],
            ['id' => 53, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 27,],
            ['id' => 54, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 28,],
            ['id' => 55, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 29,],
            ['id' => 56, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 1,],
            ['id' => 57, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 2,],
            ['id' => 58, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 3,],
            ['id' => 59, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 4,],
            ['id' => 60, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 5,],
            ['id' => 61, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 6,],
            ['id' => 62, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 7,],
            ['id' => 63, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 8,],
            ['id' => 64, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 9,],
            ['id' => 65, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 10,],
            ['id' => 66, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 11,],
            ['id' => 67, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 12,],
            ['id' => 68, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 13,],
            ['id' => 69, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 14,],
            ['id' => 70, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 15,],
            ['id' => 71, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 16,],
            ['id' => 72, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'productos', 'action_id' => 16,],
            ['id' => 73, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 17,],
            ['id' => 74, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 18,],
            ['id' => 75, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 19,],
            ['id' => 76, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 20,],
            ['id' => 77, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 21,],
            ['id' => 78, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 22,],
            ['id' => 79, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 23,],
            ['id' => 80, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 24,],
            ['id' => 81, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 25,],
            ['id' => 82, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 26,],
            ['id' => 83, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 27,],
            ['id' => 84, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 28,],
            ['id' => 85, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 29,],
            ['id' => 86, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 30,],
            ['id' => 87, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 31,],
            ['id' => 88, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 32,],
            ['id' => 89, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 33,],
            ['id' => 90, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 34,],
            ['id' => 91, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 35,],
            ['id' => 92, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 36,],
            ['id' => 93, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 37,],
            ['id' => 94, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 38,],
            ['id' => 95, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 39,],
            ['id' => 96, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 40,],
            ['id' => 97, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 41,],
            ['id' => 98, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 42,],
            ['id' => 99, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 43,],
            ['id' => 100, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 44,],
            ['id' => 101, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contacts', 'action_id' => 3,],
            ['id' => 102, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 1,],
            ['id' => 103, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 1,],
            ['id' => 104, 'user_id' => 1, 'action' => 'created', 'action_model' => 'manufacturadors', 'action_id' => 1,],
            ['id' => 105, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 1,],
            ['id' => 106, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 1,],
            ['id' => 107, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 2,],
            ['id' => 108, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 3,],
            ['id' => 109, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 4,],
            ['id' => 110, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 5,],
            ['id' => 111, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 6,],
            ['id' => 112, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 7,],
            ['id' => 113, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 8,],
            ['id' => 114, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 9,],
            ['id' => 115, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 10,],
            ['id' => 116, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 30,],
            ['id' => 117, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 45,],
            ['id' => 118, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 11,],
            ['id' => 119, 'user_id' => 1, 'action' => 'created', 'action_model' => 'principioactivos', 'action_id' => 31,],
            ['id' => 120, 'user_id' => 1, 'action' => 'created', 'action_model' => 'productos', 'action_id' => 46,],
            ['id' => 121, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 12,],
            ['id' => 122, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'listaexternas', 'action_id' => 7,],
            ['id' => 123, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'listaexternas', 'action_id' => 9,],
            ['id' => 124, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 13,],
            ['id' => 125, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 13,],
            ['id' => 126, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 14,],
            ['id' => 127, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 15,],
            ['id' => 128, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 15,],
            ['id' => 129, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 16,],
            ['id' => 130, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 16,],
            ['id' => 131, 'user_id' => 1, 'action' => 'created', 'action_model' => 'manufacturadors', 'action_id' => 2,],
            ['id' => 132, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 17,],
            ['id' => 133, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 18,],
            ['id' => 134, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 19,],
            ['id' => 135, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 20,],
            ['id' => 136, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 21,],
            ['id' => 137, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 22,],
            ['id' => 138, 'user_id' => 1, 'action' => 'created', 'action_model' => 'listaexternas', 'action_id' => 23,],
            ['id' => 139, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'users', 'action_id' => 1,],
            ['id' => 140, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'listaexternas', 'action_id' => 1,],

        ];

        foreach ($items as $item) {
            \App\UserAction::create($item);
        }
    }
}
